import env from 'Config/env';

// 动画的类型
export const ANIMATION_TYPES = {
    ENTRANCE: 'in',  //入场动画
    STAY: 'emphasize',  //停留动画
    EXITS: 'out',    // 出场动画
};

// 动画列表
export const animations = [
    {
        name: 'wobble',  // 动画名字
        title: '摇摆',   // 动画中文名字
        icon: '360px -200px',   // 动画图标位置
        hover: '360px -680px', // 动画hover状态时的图标位置
        duration: 1000, // 单词动画时长
        iteration: 1,   // 动画循环次数
        type: ANIMATION_TYPES.STAY,  // 动画类型
        text: '月圆总有星相伴',   // 动画的示例文案
        css: {
            fontSize: 35,   // 动画字的字体大小
            fontFamily: 'fangzheng_ktjt',  // 动画字的字体
            color: '#DC0000', // 动画字的字体颜色
        },
    },
    {
        name: 'rubberBand',
        title: '抖动',
        icon: '360px -160px',
        hover: '360px -640px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.STAY,
        text: '人圆总有家相随',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_htjt',
            color: '#DC0000',
        },
    },
    {
        name: 'rotate360',
        title: '旋转',
        icon: '400px -200px',
        hover: '400px -680px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.STAY,
        text: '如此良辰美景',
        css: {
            fontSize: 35,
            fontFamily: 'iekieXiaoKaiShu',
            color: '#DC0000',
        },
    },
    {
        name: 'flip',
        title: '翻转',
        icon: '200px 0px',
        hover: '200px -480px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.STAY,
        text: '应有美酒月饼',
        css: {
            fontSize: 35,
            fontFamily: 'TTCuYuanF',
            color: '#DC0000',
        },
    },
    {
        name: 'fanfare',
        title: '放大抖动',
        icon: '280px -160px',
        hover: '280px -639px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.STAY,
        text: '最好的团圆',
        css: {
            fontSize: 35,
            fontFamily: 'RZY_RuiSongCu',
            color: '#C34100',
        },
    },
    {
        name: 'fadeIn',
        title: '淡入',
        icon: '360px 0px',
        hover: '360px -480px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '是平安到家',
        css: {
            fontSize: 35,
            fontFamily: 'ZhankuxiaoweiLOGOti',
            color: '#FFAA65',
        },
    },
    {
        name: 'slideInRight',
        title: '向右移入',
        icon: '120px -80px',
        hover: '120px -560px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '一杯敬月明',
        css: {
            fontSize: 35,
            fontFamily: 'Zhankukuaileti',
            color: '#F9C9FF',
        },
    },
    {
        name: 'slideInLeft',
        title: '向左移入',
        icon: '160px -120px',
        hover: '160px -600px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '一杯敬亲情',
        css: {
            fontSize: 35,
            fontFamily: 'InpinHaiSong',
            color: '#FF2D82',
        },
    },
    {
        name: 'slideInUp',
        title: '向上移入',
        icon: '40px 0px',
        hover: '40px -480px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '70年的辉煌',
        css: {
            fontSize: 35,
            fontFamily: 'Zhankuwenyiti',
            color: '#C591FF',
        },
    },
    {
        name: 'slideInDown',
        title: '向下移入',
        icon: '160px -40px',
        hover: '160px -520px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '70年的光芒',
        css: {
            fontSize: 35,
            fontFamily: 'iekiepaomadeng',
            color: '#FF50AC',
        },
    },
    {
        name: 'bounceInRight',
        title: '向右弹入',
        icon: '240px -80px',
        hover: '240px -560px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '70载的流金岁月',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_xkjt',
            color: '#FDB7A6',
        },
    },
    {
        name: 'bounceInLeft',
        title: '向左弹入',
        icon: '280px -120px',
        hover: '280px -600px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '举杯同祝国之华诞70载',
        css: {
            fontSize: 35,
            fontFamily: 'XYouHeiTi',
            color: '#6F6F6F',
        },
    },
    {
        name: 'bounceInUp',
        title: '向上弹入',
        icon: '160px 0px',
        hover: '160px -480px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '祖国生日',
        css: {
            fontSize: 35,
            fontFamily: 'HYDianYaTiJ',
            color: '#FFD665',
        },
    },
    {
        name: 'bounceInDown',
        title: '向下弹入',
        icon: '280px -40px',
        hover: '280px -520px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '举国同庆',
        css: {
            fontSize: 35,
            fontFamily: 'RZY_SongHei',
            color: '#49C1AD',
        },
    },
    {
        name: 'flipInX',
        title: '翻开进入',
        icon: '320px -240px',
        hover: '320px -720px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '56个民族',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_dhtjt',
            color: '#5A5A5A',
        },
    },
    {
        name: 'skewSlideOutRight',
        title: '光速向右',
        icon: '320px -80px',
        hover: '320px -560px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '同一个中国',
        css: {
            fontSize: 35,
            fontFamily: 'Pangmenzhengdaobiaotiti',
            color: '#005AD6',
        },
    },
    {
        name: 'skewSlideOutLeft',
        title: '光速向左',
        icon: '360px -120px',
        hover: '360px -600px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '用七十年的沉淀',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_ytjt',
            color: '#4230B5',
        },
    },
    {
        name: 'skewSlideOutUp',
        title: '光速向上',
        icon: '280px 0px',
        hover: '280px -480px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '铸就今天的辉煌',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_ssjt',
            color: '#488A85',
        },
    },
    {
        name: 'skewSlideOutDown',
        title: '光速向下',
        icon: '360px -40px',
        hover: '360px -520px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '青春和祖国一起闪光',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_wbjt',
            color: '#9E8c00',
        },
    },
    {
        name: 'scale',
        title: '中心放大',
        icon: '280px -240px',
        hover: '280px -720px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.ENTRANCE,
        text: '光荣与梦想共同创造',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_zyjt',
            color: '#6FA07E',
        },
    },
    {
        name: 'puffIn',
        title: '由大变小',
        icon: '280px -240px',
        hover: '280px -720px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.STAY,
        text: '祝福你祖国',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_zyjt',
            color: '#FFAA65',
        },
    },
    // {
    //     name: 'magnifier',
    //     title: '放大镜',
    //     icon: '280px -240px',
    //     hover: '280px -720px',
    //     duration: 1000,
    //     iteration: 1,
    //     type: ANIMATION_TYPES.ENTRANCE,
    //     text: '我把青春献给你',
    //     css: {
    //         fontSize: 35,
    //         fontFamily: 'fangzheng_zyjt',
    //         color: '#FF50AC',
    //     },
    // },
    // 向下飞出、向上飞出、向左飞出、向右飞出、缩放、掉落
    {
        name: 'fadeBigOutUp',
        title: '向上飞出',
        icon: '120px -240px',
        hover: '120px -720px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.EXITS,
        text: '祖国之树屹立不倒',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_zyjt',
            color: '#6FA07E',
        },
    },
    {
        name: 'fadeBigOutDown',
        title: '向下飞出',
        icon: '160px -280px',
        hover: '160px -760px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.EXITS,
        text: '祖国之花永不凋谢',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_zyjt',
            color: '#FFD665',
        },
    },
    {
        name: 'fadeBigOutLeft',
        title: '向左飞出',
        icon: '280px -360px',
        hover: '280px -840px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.EXITS,
        text: '我热爱我的祖国',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_zyjt',
            color: '#DC0000',
        },
    },
    {
        name: 'fadeBigOutRight',
        title: '向右飞出',
        icon: '280px -320px',
        hover: '280px -800px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.EXITS,
        text: '我祝福我的祖国',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_zyjt',
            color: '#C591FF',
        },
    },
    {
        name: 'holeOut',
        title: '缩放',
        icon: '400px -80px',
        hover: '400px -560px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.EXITS,
        text: '少年强则国强',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_zyjt',
            color: '#C34100',
        },
    },
    {
        name: 'hinge',
        title: '掉落',
        icon: '400px -280px',
        hover: '400px -760px',
        duration: 1000,
        iteration: 1,
        type: ANIMATION_TYPES.EXITS,
        text: '少年富则国富',
        css: {
            fontSize: 35,
            fontFamily: 'fangzheng_zyjt',
            color: '#9E8c00',
        },
    },
];
//一键快闪随机动画列表
export const flashAnimates = [
    'magnifier',
    'puffIn',
    'scale',
    'skewSlideOutUp',
    'skewSlideOutDown',
    'skewSlideOutLeft',
    'skewSlideOutRight',
];

// 一键快闪不同文字长度对应不同的停留时长和字体大小（文字长度作为数组的index获取数据）
export const animateFontSize = [
    {
        duration: [300, 400],
        fontSize: [64, 150],
    },
    {
        duration: [200, 300],
        fontSize: [64, 150],
    },
    {
        duration: [200, 300],
        fontSize: [48, 96],
    },
    {
        duration: [300, 400],
        fontSize: [48, 96],
    },
    {
        duration: [300, 400],
        fontSize: [32, 64],
    },
    {
        duration: [300, 400],
        fontSize: [32, 64],
    },
    {
        duration: [400, 600],
        fontSize: [32, 48],
    },
    {
        duration: [400, 600],
        fontSize: [32, 48],
    },
    {
        duration: [400, 600],
        fontSize: [26, 45],
    },
];
//一键快闪随机字体列表
// 方正黑体简体，方正隶书简体，方正综艺体简，方正大黑简体，义启紫水晶体，庞门正道标题体，锐字工房云字库综艺GBK
export const animateFontFamily = {
    'fangzheng_htjt': {
        'ass': 'FZHei-B01S',
        'name': '方正黑体简体',
    },
    'fangzheng_lsjt': {
        'ass': 'FZLiShu-S01S',
        'name': '方正隶书简体',
    },
    'fangzheng_zyjt': {
        'ass': 'FZZongYi-M05S',
        'name': '方正综艺简体',
    },
    'fangzheng_dhtjt': {
        'name': '方正大黑简体',
        'ass': 'FZDaHei-B02S',
    },
    'iekieZiShuiJingTi': {
        'name': '义启紫水晶体',
        'ass': 'iekie zishuijingti',
    },
    'Pangmenzhengdaobiaotiti': {
        'ass': 'PangMenZhengDao',
        'name': '庞门正道标题体',
    },
    'ReejiCloudZongYiGBK': {
        'ass': 'Reeji-CloudZongYi-GB',
        'name': '锐字工房云字库综艺GBK',
    },
};
//一键快闪的随机背景色及其对应的文字颜色列表
export const animateColors = {
    '#000000': [
        '#6cf8f8',
        '#cec63f',
        '#cb682f',
        '#AD87FF',
        '#e23c73',
        '#e67637',
    ],
    '#ffffff': [
        '#ed3e3f',
        '#171717',
        '#E17000',
        '#0091DD',
        '#cc53f8',
        '#6E6E6E',
        '#009CA0',
        '#FF3E41',
    ],
    '#ff0000': [
        '#ffffff',
        '#000000',
        '#f8f863',
        '#00E8FC',
    ],
    '#ffff00': [
        '#000000',
        '#CDD8FD',
        '#656d86',
        '#ba2a26',
    ],
    '#0000ff': [
        '#000000',
        '#2758f6',
        '#fced4e',
    ],
    '#ffc0cb': [
        '#BE0500',
        '#000000',
        '#017884',
        '#5a6078',
        '#A20116',
        '#514E2D',
    ],
    '#808080': [
        '#ffffff',
        '#000000',
        '#91f1fb',
        '#001F98',
        '#72000F',
        '#fced4e',
        '#001C75',
    ],
};

//动画图示例图片
export const animateImgs = ['pre', 'pro'].includes(env.name)
    ? [
        'FrvghGYhOyubpzVkZ2E_4O3oekDK',
        'FjapX1EISqIavIzTNYjrMNljwMIs',
        'Fl_0njpjN2a8uqrAx5_7ApG7LV4q',
        'FhQzag8QxCjO5ZyjWujJfI4C_6g1',
        'lmPA6T_x5ckGAnoMaVFgedB3vgKo',
        'lvQs4eIhExY_LGD2854AUfDtXWw7',
        'Fonlj1kM_JVKU916rWzn12a5OF7L',
        'FohMHYUE4kdwEnlSMH1DiByxaHAf',
        'FnDJf6s_jsgWxYCvQARCWr0PmaRF',
        'lqjeRvqwBI8Tj0xO8ashEtZzHfxl',
        'lp66O-rM832pDIYJSjcInCMHvP6T',
        'FgNvLzJSI98qTmv5xqaSzqe7e03y',
        'FnAtOlgWcACUOvgqWM0Ulaj9XBS5',
        'Fr_L1dnSy9S8sWVq1h8TmuOnHhKx',
        'lqefOVfgsn6SMlANjMhM0sO0SwgU',
        'FjTgYJ1yz_OkDRidL8QGXOuntyBy',
        'FnEotcQ6csPQttlCfGGLgL_FBPdC',
        'FqnDaYDwz_uAI251Wl2XlX7vEZx8',
        'lpAvSIBYk_8A4_Q5wOUYyj97R3kd',
        'Fg6JpddRUiSzQD58buSd94Hyu9IC',
        'Fuoth3cRTh9NcAbdH-z_xMx34AtW',
        'Fv7Ov5cijVDGCDqCeQL2-rXiCOY2',
        'FtnazDgkzxithtLaLs61OOQFdGE1',
        'FtlyFb6D8iqZD1HiZIcQKyVyBFtY',
        'FihsqSkN_FLSoWqddSEuTvKJazbv',
        'Fn5t2pSmtNL6MvKQQISL4r1D8b0_',
        'FleG9ZyhJ3tldCbI8bWjfnsLCHV2',
        'Fi6VgaEGqeSeYjzztTtmedjoXKXW',
    ] : [
        'FrvghGYhOyubpzVkZ2E_4O3oekDK',
        'FjapX1EISqIavIzTNYjrMNljwMIs',
        'Fl_0njpjN2a8uqrAx5_7ApG7LV4q',
        'FhQzag8QxCjO5ZyjWujJfI4C_6g1',
        'lmPA6T_x5ckGAnoMaVFgedB3vgKo',
        'lvQs4eIhExY_LGD2854AUfDtXWw7',
        'Fonlj1kM_JVKU916rWzn12a5OF7L',
        'FohMHYUE4kdwEnlSMH1DiByxaHAf',
        'FnDJf6s_jsgWxYCvQARCWr0PmaRF',
        'FnAtOlgWcACUOvgqWM0Ulaj9XBS5',
        'Fr_L1dnSy9S8sWVq1h8TmuOnHhKx',
        'FqnDaYDwz_uAI251Wl2XlX7vEZx8',
        'lpAvSIBYk_8A4_Q5wOUYyj97R3kd',
        'lqjeRvqwBI8Tj0xO8ashEtZzHfxl',
        'lp66O-rM832pDIYJSjcInCMHvP6T',
        'FgNvLzJSI98qTmv5xqaSzqe7e03y',
        'lqefOVfgsn6SMlANjMhM0sO0SwgU',
        'FjTgYJ1yz_OkDRidL8QGXOuntyBy',
        'FnEotcQ6csPQttlCfGGLgL_FBPdC',
        'Fg6JpddRUiSzQD58buSd94Hyu9IC',
        'Fuoth3cRTh9NcAbdH-z_xMx34AtW',
        'Fv7Ov5cijVDGCDqCeQL2-rXiCOY2'];
//一键快闪随机音乐列表
export const bgms = ['pre', 'pro'].includes(env.name)
    ? [
        'Fp6gJVh1-gXZ3-PaDqlsyg6Y4h1G',
        'FspSJqKbn7nmk6MMpLQ61qCqICM4',
        'FgI3BCDvdgXaawNtP1kEQenl_-cM',
        'Fkyes3m9Cgx7rP5g1nHVqWmO0QwY',
        'Fuz2QhkC90iwtS06xPDJ4ZMCaiXR',
        'Fr2nSN_UJHRzilCwv9B8w89nyttC',
        'Fo1t_gfeDddCY4JDgkEN_PHuVFWN',
        'FvOhrqfMB90lDwZ7mzOTKZFPRk9y',
        'FsLWjdjH6RzHWeiWIeLkqGWQN6uI',
        'FjcA_QtRbsOJcchjQM9x67A0RNkc',
        'Fl5LMPG-bPXGh1KXRfcGWNzirIlC',
        'FvuGJSH_U3WOMqNvLuC40KzL20MM',
        'FhOrNd7J9J7SV0x0PI0FF68Tediq',
        'FuET3Q4znh4QcRMfp8Qg-t9didUN',
        'FhzBPY4fsBSRZwrJ0Wvz1ueELXsW',
        'FrJ8UdcHpvlesxk8X62uAWjopGxk',
        'FsOyiy8FcGguv2eKnyMUYf6uU0rh',
        'FvGtUvm9qV5e2hax7uJQCP1jyl8x',
        'FprD3mZd8-wwkYZaqxqd0d6NINbf',
        'FplWwUB652r2oFp1k0-1vwSTumby']
    : [
        'FvOhrqfMB90lDwZ7mzOTKZFPRk9y',
        'Fkyes3m9Cgx7rP5g1nHVqWmO0QwY',
        'Fuz2QhkC90iwtS06xPDJ4ZMCaiXR',
        'Fr2nSN_UJHRzilCwv9B8w89nyttC',
        'Fo1t_gfeDddCY4JDgkEN_PHuVFWN',
        'FsLWjdjH6RzHWeiWIeLkqGWQN6uI',
        'Fp6gJVh1-gXZ3-PaDqlsyg6Y4h1G',
        'FjcA_QtRbsOJcchjQM9x67A0RNkc',
        'FspSJqKbn7nmk6MMpLQ61qCqICM4',
        'Fl5LMPG-bPXGh1KXRfcGWNzirIlC',
        'FgI3BCDvdgXaawNtP1kEQenl_-cM',
        'FvuGJSH_U3WOMqNvLuC40KzL20MM',
        'FhOrNd7J9J7SV0x0PI0FF68Tediq',
        'FuET3Q4znh4QcRMfp8Qg-t9didUN',
        'FhzBPY4fsBSRZwrJ0Wvz1ueELXsW',
        'FrJ8UdcHpvlesxk8X62uAWjopGxk',
        'FsOyiy8FcGguv2eKnyMUYf6uU0rh',
        'FvGtUvm9qV5e2hax7uJQCP1jyl8x',
        'FprD3mZd8-wwkYZaqxqd0d6NINbf',
        'FplWwUB652r2oFp1k0-1vwSTumby'];
